### ISSUE TITLE
KeyError: 'HRNet is not in the backbone registry'

### ISSUE THREAD

**Issue by YijianLiu** [HRNet/HRNet-Object-Detection#24]
I meet an error and I don't know how to solve it, could you help me?
2019-09-25 08:15:32,758 - INFO - Distributed training: True
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 82, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 51, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 31, in build
    return _build_module(cfg, registry, default_args)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 23, in _build_module
    return obj_type(**args)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/detectors/faster_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/detectors/two_stage.py", line 27, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 35, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 31, in build
    return _build_module(cfg, registry, default_args)
  File "/home/cartur/.local/lib/python3.7/site-packages/mmdet-0.6rc0+unknown-py3.7.egg/mmdet/models/builder.py", line 15, in _build_module
    obj_type, registry.name))
KeyError: 'HRNet is not in the backbone registry'

**Comment by wondervictor** [comment]
In this repo, backbone registry is defined as "HighResolutionNet".
https://github.com/HRNet/HRNet-Object-Detection/blob/e9261d58a54c2a7e69b81295d58d52c10ea5c791/configs/hrnet/faster_rcnn_hrnetv2p_w18_2x.py#L6

While in the official [mmdetection](https://github.com/open-mmlab/mmdetection). 'HRNet' is the backbone registry
