### ISSUE TITLE
RuntimeError: The expanded size of the tensor (0) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [0].  Tensor sizes: [4]

### ISSUE THREAD

**Issue by YijianLiu** [HRNet/HRNet-Object-Detection#25]
Excuse me, I have met this error when I try to train my own data, but I don't know how to solve this error, help,help!!!Thanks!!! 

 "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/home/cartur/HRNet-Object-Detection-master/tools/train.py", line 97, in <module>
    main()
  File "/home/cartur/HRNet-Object-Detection-master/tools/train.py", line 93, in main
    logger=logger)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/apis/train.py", line 127, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/cartur/.conda/envs/CornerNet_Lite/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/cartur/.conda/envs/CornerNet_Lite/lib/python3.7/site-packages/mmcv-0.2.13-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/apis/train.py", line 37, in batch_processor
    losses = model(**data)
  File "/home/cartur/.conda/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cartur/.conda/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cartur/.conda/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/models/detectors/base.py", line 80, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/models/detectors/two_stage.py", line 136, in forward_train
    sampling_results, gt_bboxes, gt_labels, self.train_cfg.rcnn)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/models/bbox_heads/bbox_head.py", line 80, in get_target
    target_stds=self.target_stds)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/core/bbox/bbox_target.py", line 25, in bbox_target
    target_stds=target_stds)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/core/bbox/bbox_target.py", line 62, in bbox_target_single
    labels, reg_classes)
  File "/home/cartur/HRNet-Object-Detection-master/mmdet/core/bbox/bbox_target.py", line 74, in expand_target
    bbox_targets_expand[i, start:end] = bbox_targets[i, :]
RuntimeError: The expanded size of the tensor (0) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [0].  Tensor sizes: [4]

Process finished with exit code 1

**Comment by wondervictor** [comment]
I need to know:
(1) your config
(2) your data format

**Comment by YijianLiu** [comment]
I use my own data about object detection made in coco format, 
and in my config, I use faster_rcnn_hrnetv2p_w18_1x.py, and only change the root of my data and the num classes and nothing, I think it can run but not, whether other things I have to change?
Thanks!

**Comment by YijianLiu** [comment]
> I need to know:
> (1) your config
> (2) your data format

I use my own data about object detection made in coco format,
and in my config, I use faster_rcnn_hrnetv2p_w18_1x.py, and only change the root of my data and the num classes and nothing, I think it can run but not, whether other things I have to change?
Thanks!
